### ISSUE TITLE
动态加载权限菜单、按钮

### ISSUE THREAD

**Issue by myronBob** [watchdog-framework/watchdog-framework-web#1]
你好，前端是否没有实现动态读取权限菜单进行渲染？

在main.vue里面getPermission方法是读取了该用户的权限菜单集合，但是前端好像并没有使用到

**Comment by Licoy** [comment]
目前前端方面暂时未完成动态路由方面的开发，但是后续会添加此功能并作出对应的调整，感谢您对我们的关注！

**Comment by Licoy** [comment]
目前已经实现该功能，请查看分支 [0.2.x](https://github.com/watchdog-framework/watchdog-framework-web/tree/0.2.x)
